const assert = require('node:assert/strict');
const path = require('node:path');
const test = require('node:test');
const { logicalSourcePath, SvnSourceWatcher } = require('../src/svn/source-watcher');

test('maps a controlled working-copy file back to its logical authorized path', () => {
  const root = path.resolve('/checkout/pages/SYS-1');
  assert.equal(
    logicalSourcePath({ root, localSubdir: 'pages/SYS-1' }, path.join(root, '0', 'PG-1.json')),
    'pages/SYS-1/0/PG-1.json'
  );
});

test('maps a repository-root working copy without adding a physical subdirectory', () => {
  const root = path.resolve('/checkout/demo');
  assert.equal(
    logicalSourcePath({ root, localSubdir: '.' }, path.join(root, 'datasources', '0002', 'tables', 'PR_COMPANY.json')),
    'datasources/0002/tables/PR_COMPANY.json'
  );
});

test('ignores files outside the working copy, SVN metadata and unsupported extensions', () => {
  const root = path.resolve('/checkout/pages/SYS-1');
  assert.equal(logicalSourcePath({ root, localSubdir: 'pages/SYS-1' }, '/outside/PG-1.json'), undefined);
  assert.equal(logicalSourcePath({ root, localSubdir: 'pages/SYS-1' }, path.join(root, '.svn', 'wc.db')), undefined);
  assert.equal(logicalSourcePath({ root, localSubdir: 'pages/SYS-1' }, path.join(root, 'image.png')), undefined);
});

test('suppresses the watcher event generated by a managed virtual save', () => {
  let reindexed = false;
  const watcher = new SvnSourceWatcher({
    vscode: {},
    backend: { reindexFile: async () => { reindexed = true; } },
    onChanged: async () => {},
    debounceMs: 0,
  });
  const root = path.resolve('/checkout/pages/SYS-1');
  const sourcePath = 'pages/SYS-1/0/PG-1.json';
  watcher.suppress('products.demo', sourcePath);
  watcher._schedule(
    { workspaceKey: 'products.demo' },
    { root, localSubdir: 'pages/SYS-1' },
    { fsPath: path.join(root, '0', 'PG-1.json') }
  );
  assert.equal(reindexed, false);
  assert.equal(watcher.timers.size, 0);
  watcher.dispose();
});

test('suppression cancels watcher work already queued before an SVN update', async () => {
  let reindexed = false;
  const watcher = new SvnSourceWatcher({
    vscode: {},
    backend: { reindexFile: async () => { reindexed = true; } },
    onChanged: async () => {},
    debounceMs: 10,
  });
  const root = path.resolve('/checkout/pages/SYS-1');
  const sourcePath = 'pages/SYS-1/0/PG-1.json';
  watcher._schedule(
    { workspaceKey: 'products.demo' },
    { root, localSubdir: 'pages/SYS-1' },
    { fsPath: path.join(root, '0', 'PG-1.json') }
  );

  watcher.suppress('products.demo', sourcePath);
  await new Promise((resolve) => setTimeout(resolve, 20));

  assert.equal(reindexed, false);
  assert.equal(watcher.timers.size, 0);
  watcher.dispose();
});

test('flushes one batch per workspace and reports a single cascade refresh', async () => {
  const reindexed = [];
  const changes = [];
  const watcher = new SvnSourceWatcher({
    vscode: {},
    backend: {
      reindexFile: async (workspaceKey, sourcePath) => {
        reindexed.push(sourcePath);
        return { ok: true, sourcePath };
      },
    },
    onChanged: async (workspaceKey, result) => { changes.push({ workspaceKey, result }); },
    debounceMs: 5,
  });
  const root = path.resolve('/checkout/pages/SYS-1');
  const workspace = { workspaceKey: 'products.demo' };
  const workingCopy = { root, localSubdir: 'pages/SYS-1' };
  watcher._schedule(workspace, workingCopy, { fsPath: path.join(root, '0', 'PG-1.json') });
  watcher._schedule(workspace, workingCopy, { fsPath: path.join(root, '0', 'PG-2.json') });

  // 同一工作区只保留一个待处理批次。
  assert.equal(watcher.timers.size, 1);
  await new Promise((resolve) => setTimeout(resolve, 40));

  assert.deepEqual(reindexed.sort(), ['pages/SYS-1/0/PG-1.json', 'pages/SYS-1/0/PG-2.json']);
  assert.equal(changes.length, 1);
  assert.equal(changes[0].workspaceKey, 'products.demo');
  assert.deepEqual(changes[0].result.paths.sort(), ['pages/SYS-1/0/PG-1.json', 'pages/SYS-1/0/PG-2.json']);
  assert.equal(changes[0].result.ok, true);
  watcher.dispose();
});
